# Generated by Django 4.1.3 on 2022-11-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
